# Generated by Django 3.0.2 on 2020-01-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaturasAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nif',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
