# Generated by Django 3.0.2 on 2020-01-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaturasAPI', '0002_auto_20200121_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nif',
            field=models.IntegerField(default='000000000'),
        ),
    ]
