# Generated by Django 3.0.2 on 2020-01-22 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FaturasAPI', '0004_auto_20200122_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfinal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
