# Generated by Django 3.0.2 on 2020-01-24 12:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaturasAPI', '0006_auto_20200123_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='pdf',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/pdfs'), upload_to=''),
        ),
    ]
